# Generated by Django 4.2.1 on 2024-04-22 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectroCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('price', models.IntegerField(default=0)),
                ('photo', models.ImageField(blank=True, default=None, upload_to='electronics')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electronics', to='electronicsapp.electrocategory')),
            ],
        ),
    ]
