# Generated by Django 4.2.1 on 2024-04-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronicsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicsmodel',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
