# Generated by Django 4.2.1 on 2024-04-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronicsapp', '0002_electronicsmodel_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('up_to', models.DateTimeField(default=None)),
                ('photo', models.ImageField(blank=True, default=None, upload_to='offers')),
                ('content', models.TextField(blank=True)),
            ],
        ),
    ]
