# Generated by Django 4.2.1 on 2024-04-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronicsapp', '0003_offermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermodel',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
