# Generated by Django 4.2.1 on 2024-04-22 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electronicsapp', '0004_offermodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicsmodel',
            name='is_available',
            field=models.BooleanField(default=False, verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='electronicsmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electronics', to='electronicsapp.electrocategory', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='electronicsmodel',
            name='content',
            field=models.TextField(blank=True, verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='electronicsmodel',
            name='name',
            field=models.CharField(max_length=150, verbose_name="Nom de l'appareil électronique"),
        ),
        migrations.AlterField(
            model_name='electronicsmodel',
            name='photo',
            field=models.ImageField(blank=True, default=None, upload_to='electronics', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='electronicsmodel',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='electronicsmodel',
            name='slug',
            field=models.SlugField(max_length=150, unique=True, verbose_name='URL'),
        ),
    ]
